FROM python:3.8

WORKDIR /home

ADD requirements.txt requirements.txt
ADD ring/anomal/dagmm/requirements.txt ring/anomal/dagmm/requirements.txt

RUN --mount=type=cache,target=/root/.cache pip install -U pip -i https://mirrors.aliyun.com/pypi/simple/
RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
RUN --mount=type=cache,target=/root/.cache pip install -r ring/anomal/dagmm/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

ADD ring/common ring/common
ADD ring/anomal/dagmm ring/anomal/dagmm

ENV PYTHONPATH=/home
ENTRYPOINT ["python", "/home/ring/anomal/dagmm/main.py"]